from __future__ import annotations


AUTO_FALSE_FIELDS = {
    "can_auto_download": False,
    "can_auto_install": False,
    "can_auto_enable": False,
    "can_auto_execute": False,
    "can_connect_mcp": False,
    "can_call_external_api": False,
    "can_modify_system": False,
    "can_spend_money": False,
}


def candidate(
    code: str,
    name: str,
    candidate_type: str,
    vendor: str,
    description: str,
    use_case: str,
    employee: str,
    department: str,
    risk: str,
    cost: str,
    permission: str,
    stage: str,
    forbidden: list[str],
    notes: list[str],
    next_step: str,
    approval: bool,
) -> dict:
    return {
        "candidate_code": code,
        "candidate_name": name,
        "candidate_type": candidate_type,
        "vendor": vendor,
        "official_url": f"{vendor.lower().replace(' ', '-')}.example",
        "description": description,
        "use_case": use_case,
        "target_employee": employee,
        "target_department": department,
        "risk_level": risk,
        "cost_level": cost,
        "permission_level": permission,
        "requires_boss_confirmation": approval,
        "recommended_stage": stage,
        "forbidden_actions": forbidden,
        "safety_notes": notes,
        "next_step_suggestion": next_step,
        "approval_required": approval,
        **AUTO_FALSE_FIELDS,
    }


CANDIDATES = [
    candidate(
        "skill_prompt_research",
        "Prompt Research Skill",
        "skill",
        "Internal",
        "研究提示词结构、变量和安全边界。",
        "产品设计、SOP 草案和研究报告摘要。",
        "tiandao",
        "AI产品经理中心",
        "medium",
        "low",
        "research_only",
        "sprint16_candidate",
        ["auto_execute_prompt", "save_prompt_template"],
        ["只研究模板结构", "不返回完整 Prompt 原文"],
        "进入 Sprint 16 前补充天检验收规则。",
        True,
    ),
    candidate(
        "skill_frontend_observation",
        "Frontend Observation Skill",
        "skill",
        "Internal",
        "研究前端页面观察和只读检查能力。",
        "页面标题、模块、菜单入口和只读安全边界检查。",
        "tianyan_frontend",
        "前端联调优化",
        "medium",
        "low",
        "research_only",
        "sprint16_candidate",
        ["browser_click", "browser_form_fill"],
        ["只允许页面观察", "禁止自动点击和填表"],
        "后续只允许接入浏览器只读截图或 DOM 检查。",
        True,
    ),
    candidate(
        "skill_security_review_rules",
        "Security Review Rules Skill",
        "skill",
        "Internal",
        "研究安全审计规则库和危险能力识别。",
        "天监审计、敏感字段检查和危险调用 grep。",
        "tianjian_audit",
        "AI审计中心",
        "high",
        "low",
        "boss_confirm_required",
        "research_only",
        ["auto_fix_permission", "auto_update_policy"],
        ["只输出审计建议", "不自动修改权限"],
        "需要老板确认后才能进入半自动审计建议阶段。",
        True,
    ),
    candidate(
        "plugin_typeless_research",
        "Typeless Research Plugin",
        "plugin",
        "Typeless",
        "研究语音输入类插件的人工使用价值。",
        "老板口述需求和产品文档草稿输入。",
        "tiandao",
        "AI产品经理中心",
        "medium",
        "medium",
        "research_only",
        "manual_trial_candidate",
        ["auto_download", "auto_install", "auto_enable"],
        ["只展示研究结论", "不下载插件"],
        "先人工试用，再由天监评估隐私边界。",
        True,
    ),
    candidate(
        "plugin_figma_research",
        "Figma Plugin Research",
        "plugin",
        "Figma",
        "研究设计插件对天创和天颜的辅助价值。",
        "设计稿标注、页面视觉检查和素材协作。",
        "tianchuang",
        "设计中心",
        "medium",
        "medium",
        "research_only",
        "manual_trial_candidate",
        ["auto_install", "auto_modify_design"],
        ["不连接真实 Figma 项目", "不修改设计稿"],
        "补充设计权限审计后再决定是否进入人工试用。",
        True,
    ),
    candidate(
        "plugin_local_file_indexer",
        "Local File Indexer Research",
        "plugin",
        "Local Tool",
        "研究本地文件索引插件的知识资产价值。",
        "天藏知识资料索引和文档检索。",
        "tiancang",
        "知识资产中心",
        "critical",
        "low",
        "forbidden",
        "blocked",
        ["auto_scan_file", "read_local_file", "upload_file"],
        ["第一阶段禁止接入", "必须先定义文件范围和脱敏规则"],
        "保留研究记录，暂不进入 Sprint 16。",
        True,
    ),
    candidate(
        "mcp_github_readonly",
        "GitHub MCP Readonly Research",
        "mcp",
        "GitHub",
        "研究 GitHub MCP 只读仓库分析能力。",
        "代码库结构、提交差异和测试文件只读分析。",
        "tianwang",
        "后端开发中心",
        "high",
        "low",
        "boss_confirm_required",
        "research_only",
        ["git_commit", "git_push", "create_pull_request"],
        ["不连接真实 GitHub API", "不提交代码"],
        "需要天监确认权限范围后才能进入只读连接设计。",
        True,
    ),
    candidate(
        "mcp_browser_view",
        "Browser MCP View Research",
        "mcp",
        "Browser Vendor",
        "研究浏览器 MCP 只读观察能力。",
        "前端页面实测、标题检查和首屏模块检查。",
        "tianyan_frontend",
        "前端联调优化",
        "high",
        "low",
        "boss_confirm_required",
        "research_only",
        ["browser_click", "browser_form_fill", "browser_upload"],
        ["不调用浏览器自动化", "不提交表单"],
        "仅允许进入只读页面观察方案设计。",
        True,
    ),
    candidate(
        "mcp_database_readonly",
        "Database MCP Readonly Research",
        "mcp",
        "Database Vendor",
        "研究数据库只读 MCP 的风险边界。",
        "指标核对和只读数据字典研究。",
        "tianshu",
        "数据分析中心",
        "critical",
        "medium",
        "forbidden",
        "blocked",
        ["connect_database", "execute_query", "modify_schema"],
        ["第一阶段不连接数据库", "不读取真实业务数据"],
        "暂不进入 Sprint 16，先补齐脱敏与审计设计。",
        True,
    ),
    candidate(
        "tool_1688_supplier_research",
        "1688 Supplier Research Tool",
        "external_tool",
        "1688",
        "研究供应链找厂外部工具的人工检索价值。",
        "天链供应商候选检索和字段整理。",
        "tianlian",
        "供应链找厂中心",
        "medium",
        "medium",
        "research_only",
        "sprint16_candidate",
        ["auto_contact_supplier", "auto_place_order", "auto_call_external_api"],
        ["不请求外部平台", "不联系供应商"],
        "可进入 Sprint 16 做人工检索 SOP 研究。",
        True,
    ),
    candidate(
        "tool_ad_budget_research",
        "Ad Budget Research Tool",
        "external_tool",
        "Ad Platform",
        "研究广告预算工具的风险和审批边界。",
        "天投广告预算分析和人工审批建议。",
        "tiantou",
        "广告投放中心",
        "critical",
        "high",
        "forbidden",
        "blocked",
        ["modify_budget", "spend_money", "auto_submit_campaign"],
        ["禁止自动花钱", "禁止自动改预算"],
        "必须保持禁止接入，直到资金权限体系成熟。",
        True,
    ),
    candidate(
        "tool_seo_research",
        "SEO / GEO Research Tool",
        "external_tool",
        "Search Platform",
        "研究 SEO / GEO 内容工具的人工分析价值。",
        "天誉品牌增长、关键词趋势和内容建议。",
        "tianyu",
        "GEO品牌增长中心",
        "medium",
        "low",
        "research_only",
        "sprint16_candidate",
        ["auto_publish_content", "auto_call_external_api"],
        ["不自动发布", "不请求外部平台"],
        "可进入 Sprint 16 做人工内容研究流程。",
        True,
    ),
]


RISK_LEVELS = [
    {
        "risk_level": "low",
        "risk_name": "低风险",
        "description": "仅用于只读展示或人工研究，不触达外部账号和系统状态。",
        "requires_boss_confirmation": False,
        "can_enter_sprint16": True,
    },
    {
        "risk_level": "medium",
        "risk_name": "中风险",
        "description": "可能涉及外部账号、内容发布前置环节或人工试用，需要老板确认。",
        "requires_boss_confirmation": True,
        "can_enter_sprint16": True,
    },
    {
        "risk_level": "high",
        "risk_name": "高风险",
        "description": "涉及代码、浏览器、外部平台或权限边界，第一阶段仅研究。",
        "requires_boss_confirmation": True,
        "can_enter_sprint16": False,
    },
    {
        "risk_level": "critical",
        "risk_name": "极高风险",
        "description": "涉及资金、数据库、系统执行或权限变更，禁止自动化。",
        "requires_boss_confirmation": True,
        "can_enter_sprint16": False,
    },
]


COST_LEVELS = [
    {"cost_level": "free", "cost_name": "免费", "description": "无需新增成本。", "requires_boss_confirmation": False},
    {"cost_level": "low", "cost_name": "低成本", "description": "低成本人工研究。", "requires_boss_confirmation": False},
    {"cost_level": "medium", "cost_name": "中成本", "description": "可能需要订阅或人工试用成本。", "requires_boss_confirmation": True},
    {"cost_level": "high", "cost_name": "高成本", "description": "可能产生明显费用或预算风险。", "requires_boss_confirmation": True},
    {"cost_level": "unknown", "cost_name": "未知成本", "description": "成本未知时默认需要老板确认。", "requires_boss_confirmation": True},
]


NEXT_UPGRADES = [
    {
        "upgrade_code": "sprint16_manual_research_pipeline",
        "title": "人工研究流程管线",
        "target_module": "Skill / 插件研究中心",
        "priority": "high",
        "allowed_stage": "manual_research_only",
        "forbidden_actions": ["auto_download", "auto_install", "auto_execute", "call_external_api"],
        "acceptance_notes": "只允许生成研究报告，不接入真实外部能力。",
    },
    {
        "upgrade_code": "sprint16_boss_approval_matrix",
        "title": "老板审批矩阵",
        "target_module": "老板驾驶舱",
        "priority": "medium",
        "allowed_stage": "readonly_approval_advice",
        "forbidden_actions": ["auto_approve", "auto_grant_permission"],
        "acceptance_notes": "只展示审批建议，不自动批准。",
    },
]
