FROM nginx:1.27-alpine@sha256:65645c7bb6a0661892a8b03b89d0743208a18dd2f3f17a54ef4b76fb8e2f2a10

ARG NGINX_CONF=nginx/default.conf
ARG RELEASE_COMMIT=unknown
ARG BUILD_TIME=unknown
LABEL org.opencontainers.image.revision=${RELEASE_COMMIT}
LABEL org.opencontainers.image.created=${BUILD_TIME}
COPY ${NGINX_CONF} /etc/nginx/conf.d/default.conf
COPY frontend /usr/share/nginx/html

EXPOSE 80
