"""align v1 schema metadata

Revision ID: 0027_v1_schema_alignment
Revises: 0026_sprint26_ai_employee_execution_mvp
Create Date: 2026-07-11
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


revision = "0027_v1_schema_alignment"
down_revision = "0026_sprint26_ai_employee_execution_mvp"
branch_labels = None
depends_on = None


def upgrade():
    if op.get_bind().dialect.name == "sqlite":
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('account_templates', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('account_templates', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('account_templates', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('ai_capabilities', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('ai_capabilities', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('ai_employees', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('ai_employees', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('ai_tasks', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('ai_tasks', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('ai_tasks', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('brain_approval_records', 'timestamp',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('brain_execution_events', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('brain_execution_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('brain_execution_recovery', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('brain_execution_runs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_brain_execution_runs_timeout_seconds'), table_name='brain_execution_runs')
    op.alter_column('brain_orchestrator_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('brain_task_edges', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('brain_task_graphs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('brain_task_graphs_graph_id_key'), 'brain_task_graphs', type_='unique')
    op.drop_index(op.f('ix_brain_task_graphs_graph_id'), table_name='brain_task_graphs')
    op.create_index(op.f('ix_brain_task_graphs_graph_id'), 'brain_task_graphs', ['graph_id'], unique=True)
    op.alter_column('brain_task_nodes', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('brain_tool_calls', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('brain_worker_status', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('brain_worker_status', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_brain_worker_status_created_at'), 'brain_worker_status', ['created_at'], unique=False)
    op.alter_column('brands', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('brands', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('brands', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('bug_cases', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('bug_cases', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('course_lessons', 'lesson_order',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('course_lessons', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('course_lessons', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('deploy_health_checks', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('deploy_records', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('deploy_records', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('dispatch_records', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('employee_capabilities', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('employee_execution_contracts', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('employee_execution_contracts', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('employee_execution_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('employee_growth', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('employee_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('employee_scores', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('employee_store_assignments', 'role_name',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('employee_store_assignments', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('employee_store_assignments', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('employee_store_assignments', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('execution_context', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('jd_accounts', 'login_status',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'unknown'::character varying"))
    op.alter_column('jd_accounts', 'cookie_status',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'unknown'::character varying"))
    op.alter_column('jd_accounts', 'auth_status',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('jd_accounts', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('jd_accounts', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('jd_accounts', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('jd_ads', 'ad_spend',
               existing_type=sa.NUMERIC(precision=14, scale=2),
               nullable=False)
    op.alter_column('jd_ads', 'clicks',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('jd_ads', 'impressions',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('jd_ads', 'roi',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False)
    op.alter_column('jd_ads', 'cpa',
               existing_type=sa.NUMERIC(precision=14, scale=2),
               nullable=False)
    op.alter_column('jd_ads', 'deal_amount',
               existing_type=sa.NUMERIC(precision=14, scale=2),
               nullable=False)
    op.alter_column('jd_ads', 'synced_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('jd_daily_metrics', 'gmv',
               existing_type=sa.NUMERIC(precision=14, scale=2),
               nullable=False)
    op.alter_column('jd_daily_metrics', 'profit_amount',
               existing_type=sa.NUMERIC(precision=14, scale=2),
               nullable=False)
    op.alter_column('jd_daily_metrics', 'visitors_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('jd_daily_metrics', 'paid_orders_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('jd_daily_metrics', 'ad_spend',
               existing_type=sa.NUMERIC(precision=14, scale=2),
               nullable=False)
    op.alter_column('jd_daily_metrics', 'roi',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False)
    op.alter_column('jd_daily_metrics', 'refunds_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('jd_daily_metrics', 'after_sales_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('jd_daily_metrics', 'favorites_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('jd_daily_metrics', 'cart_add_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('jd_daily_metrics', 'conversion_rate',
               existing_type=sa.NUMERIC(precision=10, scale=4),
               nullable=False)
    op.alter_column('jd_daily_metrics', 'source',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('jd_daily_metrics', 'synced_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('jd_daily_metrics', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('jd_daily_metrics', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('jd_integrations', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('jd_integrations', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('jd_integrations', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('jd_integrations', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('jd_orders', 'paid_amount',
               existing_type=sa.NUMERIC(precision=14, scale=2),
               nullable=False)
    op.alter_column('jd_orders', 'profit_amount',
               existing_type=sa.NUMERIC(precision=14, scale=2),
               nullable=False)
    op.alter_column('jd_orders', 'synced_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('jd_products', 'stock_quantity',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('jd_products', 'sales_amount',
               existing_type=sa.NUMERIC(precision=14, scale=2),
               nullable=False)
    op.alter_column('jd_products', 'sales_quantity',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('jd_products', 'visitors_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('jd_products', 'conversion_rate',
               existing_type=sa.NUMERIC(precision=10, scale=4),
               nullable=False)
    op.alter_column('jd_products', 'synced_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('jd_sync_logs', 'attempt',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('jd_sync_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('knowledge_articles', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('knowledge_articles', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('knowledge_feedback', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('knowledge_files', 'file_size',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('knowledge_files', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('knowledge_files', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('metrics_daily', 'sales_amount',
               existing_type=sa.NUMERIC(precision=14, scale=2),
               nullable=False)
    op.alter_column('metrics_daily', 'profit_amount',
               existing_type=sa.NUMERIC(precision=14, scale=2),
               nullable=False)
    op.alter_column('metrics_daily', 'ad_spend',
               existing_type=sa.NUMERIC(precision=14, scale=2),
               nullable=False)
    op.alter_column('metrics_daily', 'roi',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False)
    op.alter_column('metrics_daily', 'orders_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('metrics_daily', 'visitors_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('metrics_daily', 'refunds_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('metrics_daily', 'after_sales_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('metrics_daily', 'source',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('metrics_daily', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('metrics_daily', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('orchestrator_analysis_records', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_orchestrator_analysis_records_completion'), table_name='orchestrator_analysis_records')
    op.drop_index(op.f('ix_orchestrator_analysis_records_employee_code'), table_name='orchestrator_analysis_records')
    op.drop_index(op.f('ix_orchestrator_analysis_records_sprint'), table_name='orchestrator_analysis_records')
    op.drop_index(op.f('ix_orchestrator_analysis_records_stage'), table_name='orchestrator_analysis_records')
    op.create_index(op.f('ix_orchestrator_analysis_records_completion_status'), 'orchestrator_analysis_records', ['completion_status'], unique=False)
    op.create_index(op.f('ix_orchestrator_analysis_records_detected_employee_code'), 'orchestrator_analysis_records', ['detected_employee_code'], unique=False)
    op.create_index(op.f('ix_orchestrator_analysis_records_detected_sprint'), 'orchestrator_analysis_records', ['detected_sprint'], unique=False)
    op.create_index(op.f('ix_orchestrator_analysis_records_detected_stage'), 'orchestrator_analysis_records', ['detected_stage'], unique=False)
    op.alter_column('orchestrator_prompt_confirmations', 'confirmed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('orchestrator_task_links', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('permissions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('prompt_library', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('prompt_library', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('release_versions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('uq_release_versions_version'), 'release_versions', type_='unique')
    op.drop_index(op.f('ix_release_versions_version'), table_name='release_versions')
    op.create_index(op.f('ix_release_versions_version'), 'release_versions', ['version'], unique=True)
    op.alter_column('review_analysis', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('risk_events', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('roles', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('skill_suggestions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('sop_library', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('sop_library', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('store_account_notes', 'cookie_status',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('store_account_notes', 'login_status',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('store_account_notes', 'account_status',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('store_account_notes', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('store_account_notes', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('store_account_notes', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('store_groups', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('store_groups', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('store_groups', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('stores', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('stores', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('stores_store_code_key'), 'stores', type_='unique')
    op.drop_index(op.f('ix_stores_store_code'), table_name='stores')
    op.create_index(op.f('ix_stores_store_code'), 'stores', ['store_code'], unique=True)
    op.alter_column('task_center_audit_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('task_center_results', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('task_center_reviews', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('task_center_tasks', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('task_center_tasks', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('task_reviews', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('tool_execution_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('tool_permissions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('tool_registry', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('tool_registry_tool_name_key'), 'tool_registry', type_='unique')
    op.drop_index(op.f('ix_tool_registry_tool_name'), table_name='tool_registry')
    op.create_index(op.f('ix_tool_registry_tool_name'), 'tool_registry', ['tool_name'], unique=True)
    op.alter_column('tool_route_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('tool_routes', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('users_username_key'), 'users', type_='unique')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=False)
    op.create_unique_constraint(op.f('users_username_key'), 'users', ['username'], postgresql_nulls_not_distinct=False)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('tool_routes', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('tool_route_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_tool_registry_tool_name'), table_name='tool_registry')
    op.create_index(op.f('ix_tool_registry_tool_name'), 'tool_registry', ['tool_name'], unique=False)
    op.create_unique_constraint(op.f('tool_registry_tool_name_key'), 'tool_registry', ['tool_name'], postgresql_nulls_not_distinct=False)
    op.alter_column('tool_registry', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('tool_permissions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('tool_execution_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('task_reviews', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('task_center_tasks', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('task_center_tasks', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('task_center_reviews', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('task_center_results', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('task_center_audit_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_stores_store_code'), table_name='stores')
    op.create_index(op.f('ix_stores_store_code'), 'stores', ['store_code'], unique=False)
    op.create_unique_constraint(op.f('stores_store_code_key'), 'stores', ['store_code'], postgresql_nulls_not_distinct=False)
    op.alter_column('stores', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('stores', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('store_groups', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('store_groups', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('store_groups', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('store_account_notes', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('store_account_notes', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('store_account_notes', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('store_account_notes', 'account_status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('store_account_notes', 'login_status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('store_account_notes', 'cookie_status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('sop_library', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('sop_library', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('skill_suggestions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('roles', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('risk_events', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('review_analysis', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_release_versions_version'), table_name='release_versions')
    op.create_index(op.f('ix_release_versions_version'), 'release_versions', ['version'], unique=False)
    op.create_unique_constraint(op.f('uq_release_versions_version'), 'release_versions', ['version'], postgresql_nulls_not_distinct=False)
    op.alter_column('release_versions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('prompt_library', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('prompt_library', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('permissions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('orchestrator_task_links', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('orchestrator_prompt_confirmations', 'confirmed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_orchestrator_analysis_records_detected_stage'), table_name='orchestrator_analysis_records')
    op.drop_index(op.f('ix_orchestrator_analysis_records_detected_sprint'), table_name='orchestrator_analysis_records')
    op.drop_index(op.f('ix_orchestrator_analysis_records_detected_employee_code'), table_name='orchestrator_analysis_records')
    op.drop_index(op.f('ix_orchestrator_analysis_records_completion_status'), table_name='orchestrator_analysis_records')
    op.create_index(op.f('ix_orchestrator_analysis_records_stage'), 'orchestrator_analysis_records', ['detected_stage'], unique=False)
    op.create_index(op.f('ix_orchestrator_analysis_records_sprint'), 'orchestrator_analysis_records', ['detected_sprint'], unique=False)
    op.create_index(op.f('ix_orchestrator_analysis_records_employee_code'), 'orchestrator_analysis_records', ['detected_employee_code'], unique=False)
    op.create_index(op.f('ix_orchestrator_analysis_records_completion'), 'orchestrator_analysis_records', ['completion_status'], unique=False)
    op.alter_column('orchestrator_analysis_records', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('metrics_daily', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('metrics_daily', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('metrics_daily', 'source',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('metrics_daily', 'after_sales_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('metrics_daily', 'refunds_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('metrics_daily', 'visitors_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('metrics_daily', 'orders_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('metrics_daily', 'roi',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
    op.alter_column('metrics_daily', 'ad_spend',
               existing_type=sa.NUMERIC(precision=14, scale=2),
               nullable=True)
    op.alter_column('metrics_daily', 'profit_amount',
               existing_type=sa.NUMERIC(precision=14, scale=2),
               nullable=True)
    op.alter_column('metrics_daily', 'sales_amount',
               existing_type=sa.NUMERIC(precision=14, scale=2),
               nullable=True)
    op.alter_column('knowledge_files', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('knowledge_files', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('knowledge_files', 'file_size',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('knowledge_feedback', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('knowledge_articles', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('knowledge_articles', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('jd_sync_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('jd_sync_logs', 'attempt',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('jd_products', 'synced_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('jd_products', 'conversion_rate',
               existing_type=sa.NUMERIC(precision=10, scale=4),
               nullable=True)
    op.alter_column('jd_products', 'visitors_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('jd_products', 'sales_quantity',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('jd_products', 'sales_amount',
               existing_type=sa.NUMERIC(precision=14, scale=2),
               nullable=True)
    op.alter_column('jd_products', 'stock_quantity',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('jd_orders', 'synced_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('jd_orders', 'profit_amount',
               existing_type=sa.NUMERIC(precision=14, scale=2),
               nullable=True)
    op.alter_column('jd_orders', 'paid_amount',
               existing_type=sa.NUMERIC(precision=14, scale=2),
               nullable=True)
    op.alter_column('jd_integrations', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('jd_integrations', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('jd_integrations', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('jd_integrations', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('jd_daily_metrics', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('jd_daily_metrics', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('jd_daily_metrics', 'synced_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('jd_daily_metrics', 'source',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('jd_daily_metrics', 'conversion_rate',
               existing_type=sa.NUMERIC(precision=10, scale=4),
               nullable=True)
    op.alter_column('jd_daily_metrics', 'cart_add_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('jd_daily_metrics', 'favorites_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('jd_daily_metrics', 'after_sales_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('jd_daily_metrics', 'refunds_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('jd_daily_metrics', 'roi',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
    op.alter_column('jd_daily_metrics', 'ad_spend',
               existing_type=sa.NUMERIC(precision=14, scale=2),
               nullable=True)
    op.alter_column('jd_daily_metrics', 'paid_orders_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('jd_daily_metrics', 'visitors_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('jd_daily_metrics', 'profit_amount',
               existing_type=sa.NUMERIC(precision=14, scale=2),
               nullable=True)
    op.alter_column('jd_daily_metrics', 'gmv',
               existing_type=sa.NUMERIC(precision=14, scale=2),
               nullable=True)
    op.alter_column('jd_ads', 'synced_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('jd_ads', 'deal_amount',
               existing_type=sa.NUMERIC(precision=14, scale=2),
               nullable=True)
    op.alter_column('jd_ads', 'cpa',
               existing_type=sa.NUMERIC(precision=14, scale=2),
               nullable=True)
    op.alter_column('jd_ads', 'roi',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
    op.alter_column('jd_ads', 'impressions',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('jd_ads', 'clicks',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('jd_ads', 'ad_spend',
               existing_type=sa.NUMERIC(precision=14, scale=2),
               nullable=True)
    op.alter_column('jd_accounts', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('jd_accounts', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('jd_accounts', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('jd_accounts', 'auth_status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('jd_accounts', 'cookie_status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'unknown'::character varying"))
    op.alter_column('jd_accounts', 'login_status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'unknown'::character varying"))
    op.alter_column('execution_context', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('employee_store_assignments', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('employee_store_assignments', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('employee_store_assignments', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('employee_store_assignments', 'role_name',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('employee_scores', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('employee_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('employee_growth', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('employee_execution_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('employee_execution_contracts', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('employee_execution_contracts', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('employee_capabilities', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('dispatch_records', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('deploy_records', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('deploy_records', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('deploy_health_checks', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('course_lessons', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('course_lessons', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('course_lessons', 'lesson_order',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('bug_cases', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('bug_cases', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('brands', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('brands', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('brands', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_index(op.f('ix_brain_worker_status_created_at'), table_name='brain_worker_status')
    op.alter_column('brain_worker_status', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('brain_worker_status', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('brain_tool_calls', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('brain_task_nodes', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_brain_task_graphs_graph_id'), table_name='brain_task_graphs')
    op.create_index(op.f('ix_brain_task_graphs_graph_id'), 'brain_task_graphs', ['graph_id'], unique=False)
    op.create_unique_constraint(op.f('brain_task_graphs_graph_id_key'), 'brain_task_graphs', ['graph_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('brain_task_graphs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('brain_task_edges', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('brain_orchestrator_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_brain_execution_runs_timeout_seconds'), 'brain_execution_runs', ['timeout_seconds'], unique=False)
    op.alter_column('brain_execution_runs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('brain_execution_recovery', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('brain_execution_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('brain_execution_events', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('brain_approval_records', 'timestamp',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('ai_tasks', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('ai_tasks', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('ai_tasks', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('ai_employees', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('ai_employees', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('ai_capabilities', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('ai_capabilities', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('account_templates', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('account_templates', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('account_templates', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
