from __future__ import annotations


DEFAULT_CAPABILITIES = [
    {
        "employee_code": "tiancai_data",
        "employee_name": "天采：数据采集平台",
        "capability_name": "数据采集",
        "capability_type": "data_collection",
        "description": "采集电商、内容、趋势和竞品基础数据，只读登记，不自动联网。",
        "enabled": True,
    },
    {
        "employee_code": "tiancai_data",
        "employee_name": "天采：数据采集平台",
        "capability_name": "Excel分析",
        "capability_type": "file_analysis",
        "description": "读取和分析 Excel 文件内容，不修改源文件。",
        "enabled": True,
    },
    {
        "employee_code": "tiancai_data",
        "employee_name": "天采：数据采集平台",
        "capability_name": "API读取",
        "capability_type": "api_read",
        "description": "登记 API 只读能力，第一阶段不调用未知外部 API。",
        "enabled": True,
    },
    {
        "employee_code": "tiancai",
        "employee_name": "天采：数据采集中心",
        "capability_name": "数据采集",
        "capability_type": "data_collection",
        "description": "采集电商、内容、趋势和竞品基础数据，只读登记，不自动联网。",
        "enabled": True,
    },
    {
        "employee_code": "tiancai",
        "employee_name": "天采：数据采集中心",
        "capability_name": "Excel分析",
        "capability_type": "file_analysis",
        "description": "读取和分析 Excel 文件内容，不修改源文件。",
        "enabled": True,
    },
    {
        "employee_code": "tiancai",
        "employee_name": "天采：数据采集中心",
        "capability_name": "API读取",
        "capability_type": "api_read",
        "description": "登记 API 只读能力，第一阶段不调用未知外部 API。",
        "enabled": True,
    },
    {
        "employee_code": "tianchuang",
        "employee_name": "天创：设计中心",
        "capability_name": "图片生成",
        "capability_type": "image_generation",
        "description": "生成图片草稿能力，真实生成前需要模型和工具权限审批。",
        "enabled": True,
    },
    {
        "employee_code": "tianchuang",
        "employee_name": "天创：设计中心",
        "capability_name": "图片评分",
        "capability_type": "image_review",
        "description": "对图片素材进行质量评分和建议，不自动发布。",
        "enabled": True,
    },
    {
        "employee_code": "tianyu",
        "employee_name": "天誉：GEO/SEO品牌增长中心",
        "capability_name": "SEO分析",
        "capability_type": "seo_analysis",
        "description": "分析搜索内容结构和关键词机会，只生成建议。",
        "enabled": True,
    },
    {
        "employee_code": "tianyu",
        "employee_name": "天誉：GEO/SEO品牌增长中心",
        "capability_name": "GEO分析",
        "capability_type": "geo_analysis",
        "description": "分析生成式搜索曝光机会，只生成建议。",
        "enabled": True,
    },
]


DEFAULT_TOOL_PERMISSIONS = [
    {
        "employee_code": "tiancai_data",
        "tool_name": "database_read",
        "permission_level": "readonly",
        "allowed": True,
        "require_approval": False,
    },
    {
        "employee_code": "tiancai_data",
        "tool_name": "api_read",
        "permission_level": "readonly",
        "allowed": True,
        "require_approval": True,
    },
    {
        "employee_code": "tiancai_data",
        "tool_name": "delete_data",
        "permission_level": "forbidden",
        "allowed": False,
        "require_approval": True,
    },
    {
        "employee_code": "tiancai_data",
        "tool_name": "unknown_api",
        "permission_level": "forbidden",
        "allowed": False,
        "require_approval": True,
    },
    {
        "employee_code": "tiancai_data",
        "tool_name": "browser_search",
        "permission_level": "research_only",
        "allowed": True,
        "require_approval": True,
    },
    {
        "employee_code": "tiancai_data",
        "tool_name": "excel_parse",
        "permission_level": "readonly",
        "allowed": True,
        "require_approval": False,
    },
    {
        "employee_code": "tiancai_data",
        "tool_name": "payment_execute",
        "permission_level": "forbidden",
        "allowed": False,
        "require_approval": True,
    },
    {
        "employee_code": "tiancai",
        "tool_name": "database_read",
        "permission_level": "readonly",
        "allowed": True,
        "require_approval": False,
    },
    {
        "employee_code": "tiancai",
        "tool_name": "api_read",
        "permission_level": "readonly",
        "allowed": True,
        "require_approval": True,
    },
    {
        "employee_code": "tiancai",
        "tool_name": "delete_data",
        "permission_level": "forbidden",
        "allowed": False,
        "require_approval": True,
    },
    {
        "employee_code": "tiancai",
        "tool_name": "unknown_api",
        "permission_level": "forbidden",
        "allowed": False,
        "require_approval": True,
    },
    {
        "employee_code": "tiancai",
        "tool_name": "excel_parse",
        "permission_level": "readonly",
        "allowed": True,
        "require_approval": False,
    },
    {
        "employee_code": "tiancai",
        "tool_name": "payment_execute",
        "permission_level": "forbidden",
        "allowed": False,
        "require_approval": True,
    },
    {
        "employee_code": "tiancai",
        "tool_name": "browser_search",
        "permission_level": "research_only",
        "allowed": True,
        "require_approval": True,
    },
    {
        "employee_code": "tiancai",
        "tool_name": "shell_execute",
        "permission_level": "forbidden",
        "allowed": False,
        "require_approval": True,
    },
    {
        "employee_code": "tiancai",
        "tool_name": "docker_control",
        "permission_level": "forbidden",
        "allowed": False,
        "require_approval": True,
    },
    {
        "employee_code": "tiancai",
        "tool_name": "git_push",
        "permission_level": "forbidden",
        "allowed": False,
        "require_approval": True,
    },
    {
        "employee_code": "tiancai",
        "tool_name": "image_generate",
        "permission_level": "draft_only",
        "allowed": True,
        "require_approval": True,
    },
    {
        "employee_code": "tianchuang",
        "tool_name": "image_generate",
        "permission_level": "draft_only",
        "allowed": True,
        "require_approval": True,
    },
    {
        "employee_code": "tianchuang",
        "tool_name": "delete_data",
        "permission_level": "forbidden",
        "allowed": False,
        "require_approval": True,
    },
    {
        "employee_code": "tianyu",
        "tool_name": "seo_analyze",
        "permission_level": "readonly",
        "allowed": True,
        "require_approval": False,
    },
    {
        "employee_code": "tianyu",
        "tool_name": "geo_analyze",
        "permission_level": "readonly",
        "allowed": True,
        "require_approval": False,
    },
    {
        "employee_code": "tiancai_finance",
        "tool_name": "financial_analysis",
        "permission_level": "readonly",
        "allowed": True,
        "require_approval": False,
    },
    {
        "employee_code": "tiancai_finance",
        "tool_name": "payment_execute",
        "permission_level": "forbidden",
        "allowed": False,
        "require_approval": True,
    },
]
