from __future__ import annotations

from typing import Final


CAPABILITY_TYPES: Final[tuple[str, ...]] = (
    "数据读取",
    "API 调用",
    "浏览器操作",
    "电脑操作",
    "手机操作",
    "文件处理",
    "数据库操作",
    "Shell 操作",
    "Git 操作",
    "Docker 操作",
    "邮件操作",
    "日历操作",
    "搜索能力",
    "AI 模型调用",
    "研究分析",
)

EXECUTOR_TYPES: Final[tuple[str, ...]] = (
    "mock",
    "real",
    "browser",
    "research",
    "desktop",
    "mobile",
    "shell",
    "api",
    "database",
    "file",
)

RISK_LEVELS: Final[tuple[str, ...]] = ("low", "medium", "high", "critical")

EXECUTION_STATUS_LABELS: Final[dict[str, str]] = {
    "pending_validation": "待校验",
    "waiting_approval": "等待审批",
    "approved": "已批准",
    "rejected": "已拒绝",
    "waiting_execution": "等待执行",
    "running": "执行中",
    "success": "执行成功",
    "failed": "执行失败",
    "cancelled": "已取消",
    "timeout": "已超时",
}

APPROVAL_STATUS_LABELS: Final[dict[str, str]] = {
    "not_required": "无需审批",
    "pending": "等待审批",
    "approved": "已批准",
    "rejected": "已拒绝",
}

AUDIT_EVENT_LABELS: Final[dict[str, str]] = {
    "execution_created": "执行已创建",
    "execution_approved": "执行已批准",
    "execution_rejected": "执行已拒绝",
    "execution_cancelled": "执行已取消",
    "execution_started": "执行已开始",
    "execution_succeeded": "执行已成功",
    "execution_failed": "执行已失败",
    "execution_timeout": "执行已超时",
    "execution_retry": "执行已重试",
}

DEFAULT_CAPABILITIES: Final[tuple[dict[str, object], ...]] = (
    {
        "capability_id": "mock.echo",
        "capability_name": "模拟回声",
        "capability_type": "文件处理",
        "description": "返回固定的模拟成功结果，用于验证 Agent Runtime 全链路。",
        "executor_type": "mock",
        "risk_level": "low",
        "enabled": True,
        "readonly": True,
        "requires_boss_approval": False,
        "requires_security_audit": False,
        "timeout_seconds": 30,
        "max_retries": 0,
        "input_schema_json": '{"type":"object","properties":{"message":{"type":"string"}},"required":["message"],"additionalProperties":true}',
        "output_schema_json": '{"type":"object","properties":{"message":{"type":"string"},"mode":{"type":"string"}},"required":["message","mode"]}',
        "allowed_employee_codes_json": '[]',
        "version": "1.0.0",
    },
    {
        "capability_id": "mock.failure",
        "capability_name": "模拟失败",
        "capability_type": "文件处理",
        "description": "固定返回失败，用于验证错误处理和审计。",
        "executor_type": "mock",
        "risk_level": "low",
        "enabled": True,
        "readonly": True,
        "requires_boss_approval": False,
        "requires_security_audit": False,
        "timeout_seconds": 30,
        "max_retries": 0,
        "input_schema_json": '{"type":"object","properties":{"message":{"type":"string"}},"required":["message"],"additionalProperties":true}',
        "output_schema_json": '{"type":"object","properties":{"message":{"type":"string"},"mode":{"type":"string"}},"required":["message","mode"]}',
        "allowed_employee_codes_json": '[]',
        "version": "1.0.0",
    },
    {
        "capability_id": "mock.timeout",
        "capability_name": "模拟超时",
        "capability_type": "文件处理",
        "description": "模拟超时场景，用于验证超时状态和审计。",
        "executor_type": "mock",
        "risk_level": "medium",
        "enabled": True,
        "readonly": True,
        "requires_boss_approval": False,
        "requires_security_audit": True,
        "timeout_seconds": 1,
        "max_retries": 0,
        "input_schema_json": '{"type":"object","properties":{"message":{"type":"string"}},"required":["message"],"additionalProperties":true}',
        "output_schema_json": '{"type":"object","properties":{"message":{"type":"string"},"mode":{"type":"string"}},"required":["message","mode"]}',
        "allowed_employee_codes_json": '[]',
        "version": "1.0.0",
    },
    {
        "capability_id": "mock.retry",
        "capability_name": "模拟重试",
        "capability_type": "文件处理",
        "description": "模拟重试场景，用于验证自动重试逻辑。",
        "executor_type": "mock",
        "risk_level": "medium",
        "enabled": True,
        "readonly": True,
        "requires_boss_approval": False,
        "requires_security_audit": True,
        "timeout_seconds": 30,
        "max_retries": 2,
        "input_schema_json": '{"type":"object","properties":{"message":{"type":"string"}},"required":["message"],"additionalProperties":true}',
        "output_schema_json": '{"type":"object","properties":{"message":{"type":"string"},"mode":{"type":"string"}},"required":["message","mode"]}',
        "allowed_employee_codes_json": '[]',
        "version": "1.0.0",
    },
    {
        "capability_id": "task.writeback",
        "capability_name": "任务结果回写",
        "capability_type": "数据库操作",
        "description": "将 V2 执行结果回写到任务摘要，仅在明确启用时生效。",
        "executor_type": "mock",
        "risk_level": "medium",
        "enabled": True,
        "readonly": False,
        "requires_boss_approval": False,
        "requires_security_audit": True,
        "timeout_seconds": 30,
        "max_retries": 0,
        "input_schema_json": '{"type":"object","properties":{"task_summary":{"type":"string"},"message":{"type":"string"}},"required":["task_summary"],"additionalProperties":true}',
        "output_schema_json": '{"type":"object","properties":{"task_summary":{"type":"string"},"linked_task_id":{"type":["string","null"]}},"required":["task_summary"]}',
        "allowed_employee_codes_json": '[]',
        "version": "1.0.0",
    },
    {
        "capability_id": "browser.public.read",
        "capability_name": "公开网页读取",
        "capability_type": "浏览器操作",
        "description": "只读访问授权公开网页，提取标题、正文、结构化字段和来源证据。",
        "executor_type": "browser",
        "risk_level": "low",
        "enabled": False,
        "readonly": True,
        "requires_boss_approval": False,
        "requires_security_audit": True,
        "timeout_seconds": 20,
        "max_retries": 1,
        "input_schema_json": '{"type":"object","properties":{"url":{"type":"string"},"extract_fields":{"type":"array"},"allow_redirects":{"type":"boolean"},"method":{"type":"string"},"timeout_seconds":{"type":"integer"},"max_response_bytes":{"type":"integer"}},"required":["url"],"additionalProperties":true}',
        "output_schema_json": '{"type":"object","properties":{"requested_url":{"type":"string"},"final_url":{"type":"string"},"page_title":{"type":["string","null"]},"status_code":{"type":"integer"},"content_type":{"type":"string"},"extracted_text":{"type":["string","null"]},"structured_fields":{"type":"object"},"sources":{"type":"array"},"collected_at":{"type":"string"},"content_hash":{"type":"string"},"duration_ms":{"type":"integer"},"redirect_chain":{"type":"array"},"domain":{"type":"string"}},"required":["requested_url","final_url","status_code","content_type","structured_fields","sources","collected_at","content_hash","duration_ms","redirect_chain","domain"]}',
        "allowed_employee_codes_json": '["tiancai_data"]',
        "version": "1.0.0",
    },
    {
        "capability_id": "research.public.multi_source",
        "capability_name": "多来源公开信息研究",
        "capability_type": "研究分析",
        "description": "将公开研究主题拆解为多查询，交叉验证来源并生成带证据链的中文研究报告。",
        "executor_type": "research",
        "risk_level": "low",
        "enabled": False,
        "readonly": True,
        "requires_boss_approval": False,
        "requires_security_audit": True,
        "timeout_seconds": 120,
        "max_retries": 1,
        "input_schema_json": '{"type":"object","properties":{"topic":{"type":"string"},"goal":{"type":"string"},"max_queries":{"type":"integer"},"max_sources":{"type":"integer"},"time_range":{"type":"string"},"language":{"type":"string"},"allowed_domains":{"type":"array","items":{"type":"string"}},"blocked_domains":{"type":"array","items":{"type":"string"}},"cross_validate":{"type":"boolean"},"min_sources":{"type":"integer"},"report_format":{"type":"string"}},"required":["topic","goal"],"additionalProperties":true}',
        "output_schema_json": '{"type":"object","properties":{"research_summary":{"type":"string"},"core_conclusions":{"type":"array"},"structured_data":{"type":"object"},"sources":{"type":"array"},"evidence":{"type":"array"},"source_reliability":{"type":"object"},"conflicts":{"type":"array"},"uncertainties":{"type":"array"},"collected_at":{"type":"string"},"trace_id":{"type":"string"},"report_hash":{"type":"string"}},"required":["research_summary","core_conclusions","structured_data","sources","evidence","source_reliability","conflicts","uncertainties","collected_at","trace_id","report_hash"]}',
        "allowed_employee_codes_json": '["tiancai_data"]',
        "version": "1.0.0",
    },
    {
        "capability_id": "computer.sandbox.observe",
        "capability_name": "隔离桌面查看",
        "capability_type": "电脑操作",
        "description": "仅用于隔离测试桌面，可查看窗口、屏幕状态和截图，不控制真实电脑。",
        "executor_type": "desktop",
        "risk_level": "low",
        "enabled": False,
        "readonly": True,
        "requires_boss_approval": False,
        "requires_security_audit": True,
        "timeout_seconds": 30,
        "max_retries": 0,
        "input_schema_json": '{"type":"object","properties":{"session_id":{"type":"string"},"include_screenshot":{"type":"boolean"}},"required":["session_id"],"additionalProperties":true}',
        "output_schema_json": '{"type":"object","properties":{"session_id":{"type":"string"},"window_title":{"type":["string","null"]},"active_application":{"type":["string","null"]},"screenshot_reference":{"type":["string","null"]},"status":{"type":"string"}},"required":["session_id","status"]}',
        "allowed_employee_codes_json": '["tiancai_data"]',
        "version": "1.0.0",
    },
    {
        "capability_id": "computer.macos.observe",
        "capability_name": "Mac 测试设备只读观察",
        "capability_type": "电脑操作",
        "description": "仅用于受控 Mac 测试设备，只读查看窗口、屏幕和状态，不控制真实电脑。",
        "executor_type": "desktop",
        "risk_level": "low",
        "enabled": False,
        "readonly": True,
        "requires_boss_approval": False,
        "requires_security_audit": True,
        "timeout_seconds": 30,
        "max_retries": 0,
        "input_schema_json": '{"type":"object","properties":{"device_id":{"type":"string"},"observation_goal":{"type":"string"},"allowed_applications":{"type":"array","items":{"type":"string"}},"allowed_windows":{"type":"array","items":{"type":"string"}},"max_screenshots":{"type":"integer"}},"required":["device_id"],"additionalProperties":true}',
        "output_schema_json": '{"type":"object","properties":{"device_id":{"type":"string"},"status":{"type":"string"},"current_application":{"type":["string","null"]},"current_window":{"type":["string","null"]},"window_count":{"type":"integer"},"screenshot_reference":{"type":["string","null"]},"screen_state":{"type":["string","null"]},"suggested_next_step":{"type":["string","null"]}},"required":["device_id","status","window_count"]}',
        "allowed_employee_codes_json": '["tianjian_test","tiancai_data"]',
        "version": "1.0.0",
    },
)
