from __future__ import annotations

from typing import Final


CAPABILITY_TYPES: Final[tuple[str, ...]] = (
    "数据读取",
    "API 调用",
    "浏览器操作",
    "电脑操作",
    "手机操作",
    "文件处理",
    "数据库操作",
    "Shell 操作",
    "Git 操作",
    "Docker 操作",
    "邮件操作",
    "日历操作",
    "搜索能力",
    "AI 模型调用",
)

EXECUTOR_TYPES: Final[tuple[str, ...]] = (
    "mock",
    "real",
    "browser",
    "desktop",
    "mobile",
    "shell",
    "api",
    "database",
    "file",
)

RISK_LEVELS: Final[tuple[str, ...]] = ("low", "medium", "high", "critical")

EXECUTION_STATUS_LABELS: Final[dict[str, str]] = {
    "pending_validation": "待校验",
    "waiting_approval": "等待审批",
    "approved": "已批准",
    "rejected": "已拒绝",
    "waiting_execution": "等待执行",
    "running": "执行中",
    "success": "执行成功",
    "failed": "执行失败",
    "cancelled": "已取消",
    "timeout": "已超时",
}

APPROVAL_STATUS_LABELS: Final[dict[str, str]] = {
    "not_required": "无需审批",
    "pending": "等待审批",
    "approved": "已批准",
    "rejected": "已拒绝",
}

AUDIT_EVENT_LABELS: Final[dict[str, str]] = {
    "execution_created": "执行已创建",
    "execution_approved": "执行已批准",
    "execution_rejected": "执行已拒绝",
    "execution_cancelled": "执行已取消",
    "execution_started": "执行已开始",
    "execution_succeeded": "执行已成功",
    "execution_failed": "执行已失败",
    "execution_timeout": "执行已超时",
    "execution_retry": "执行已重试",
}

DEFAULT_CAPABILITIES: Final[tuple[dict[str, object], ...]] = (
    {
        "capability_id": "mock.echo",
        "capability_name": "模拟回声",
        "capability_type": "文件处理",
        "description": "返回固定的模拟成功结果，用于验证 Agent Runtime 全链路。",
        "executor_type": "mock",
        "risk_level": "low",
        "enabled": True,
        "readonly": True,
        "requires_boss_approval": False,
        "requires_security_audit": False,
        "timeout_seconds": 30,
        "max_retries": 0,
        "input_schema_json": '{"type":"object","properties":{"message":{"type":"string"}},"required":["message"],"additionalProperties":true}',
        "output_schema_json": '{"type":"object","properties":{"message":{"type":"string"},"mode":{"type":"string"}},"required":["message","mode"]}',
        "allowed_employee_codes_json": '[]',
        "version": "1.0.0",
    },
    {
        "capability_id": "mock.failure",
        "capability_name": "模拟失败",
        "capability_type": "文件处理",
        "description": "固定返回失败，用于验证错误处理和审计。",
        "executor_type": "mock",
        "risk_level": "low",
        "enabled": True,
        "readonly": True,
        "requires_boss_approval": False,
        "requires_security_audit": False,
        "timeout_seconds": 30,
        "max_retries": 0,
        "input_schema_json": '{"type":"object","properties":{"message":{"type":"string"}},"required":["message"],"additionalProperties":true}',
        "output_schema_json": '{"type":"object","properties":{"message":{"type":"string"},"mode":{"type":"string"}},"required":["message","mode"]}',
        "allowed_employee_codes_json": '[]',
        "version": "1.0.0",
    },
    {
        "capability_id": "mock.timeout",
        "capability_name": "模拟超时",
        "capability_type": "文件处理",
        "description": "模拟超时场景，用于验证超时状态和审计。",
        "executor_type": "mock",
        "risk_level": "medium",
        "enabled": True,
        "readonly": True,
        "requires_boss_approval": False,
        "requires_security_audit": True,
        "timeout_seconds": 1,
        "max_retries": 0,
        "input_schema_json": '{"type":"object","properties":{"message":{"type":"string"}},"required":["message"],"additionalProperties":true}',
        "output_schema_json": '{"type":"object","properties":{"message":{"type":"string"},"mode":{"type":"string"}},"required":["message","mode"]}',
        "allowed_employee_codes_json": '[]',
        "version": "1.0.0",
    },
    {
        "capability_id": "mock.retry",
        "capability_name": "模拟重试",
        "capability_type": "文件处理",
        "description": "模拟重试场景，用于验证自动重试逻辑。",
        "executor_type": "mock",
        "risk_level": "medium",
        "enabled": True,
        "readonly": True,
        "requires_boss_approval": False,
        "requires_security_audit": True,
        "timeout_seconds": 30,
        "max_retries": 2,
        "input_schema_json": '{"type":"object","properties":{"message":{"type":"string"}},"required":["message"],"additionalProperties":true}',
        "output_schema_json": '{"type":"object","properties":{"message":{"type":"string"},"mode":{"type":"string"}},"required":["message","mode"]}',
        "allowed_employee_codes_json": '[]',
        "version": "1.0.0",
    },
    {
        "capability_id": "task.writeback",
        "capability_name": "任务结果回写",
        "capability_type": "数据库操作",
        "description": "将 V2 执行结果回写到任务摘要，仅在明确启用时生效。",
        "executor_type": "mock",
        "risk_level": "medium",
        "enabled": True,
        "readonly": False,
        "requires_boss_approval": False,
        "requires_security_audit": True,
        "timeout_seconds": 30,
        "max_retries": 0,
        "input_schema_json": '{"type":"object","properties":{"task_summary":{"type":"string"},"message":{"type":"string"}},"required":["task_summary"],"additionalProperties":true}',
        "output_schema_json": '{"type":"object","properties":{"task_summary":{"type":"string"},"linked_task_id":{"type":["string","null"]}},"required":["task_summary"]}',
        "allowed_employee_codes_json": '[]',
        "version": "1.0.0",
    },
)
