from __future__ import annotations


DEFAULT_TOOLS = [
    {
        "id": 1001,
        "tool_name": "browser_search",
        "tool_type": "web_search",
        "description": "网页搜索能力，第一阶段仅模拟权限检查和日志记录。",
        "provider": "internal",
        "version": "v1",
        "enabled": True,
        "risk_level": "high",
        "created_at": None,
    },
    {
        "id": 1002,
        "tool_name": "web_reader",
        "tool_type": "web_reader",
        "description": "公开网页读取与摘要，第一阶段不真实联网。",
        "provider": "internal",
        "version": "v1",
        "enabled": True,
        "risk_level": "medium",
        "created_at": None,
    },
    {
        "id": 1003,
        "tool_name": "file_reader",
        "tool_type": "file",
        "description": "文件读取能力登记，禁止读取敏感路径。",
        "provider": "internal",
        "version": "v1",
        "enabled": True,
        "risk_level": "medium",
        "created_at": None,
    },
    {
        "id": 1004,
        "tool_name": "excel_analyzer",
        "tool_type": "file",
        "description": "Excel 分析能力登记，第一阶段只模拟。",
        "provider": "internal",
        "version": "v1",
        "enabled": True,
        "risk_level": "low",
        "created_at": None,
    },
    {
        "id": 1005,
        "tool_name": "image_reader",
        "tool_type": "vision",
        "description": "图片理解能力登记，第一阶段不调用模型。",
        "provider": "internal",
        "version": "v1",
        "enabled": True,
        "risk_level": "medium",
        "created_at": None,
    },
    {
        "id": 1006,
        "tool_name": "api_connector",
        "tool_type": "api",
        "description": "外部 API 连接器登记，第一阶段禁止真实调用。",
        "provider": "internal",
        "version": "v1",
        "enabled": True,
        "risk_level": "high",
        "created_at": None,
    },
    {
        "id": 1007,
        "tool_name": "seo_analyzer",
        "tool_type": "analysis",
        "description": "SEO/GEO 分析能力登记。",
        "provider": "internal",
        "version": "v1",
        "enabled": True,
        "risk_level": "low",
        "created_at": None,
    },
    {
        "id": 1008,
        "tool_name": "financial_reader",
        "tool_type": "finance",
        "description": "财务数据只读分析能力，默认需要审批。",
        "provider": "internal",
        "version": "v1",
        "enabled": True,
        "risk_level": "high",
        "created_at": None,
    },
    {
        "id": 1009,
        "tool_name": "delete_data",
        "tool_type": "dangerous",
        "description": "删除数据动作，永久禁止自动执行。",
        "provider": "internal",
        "version": "v1",
        "enabled": False,
        "risk_level": "critical",
        "created_at": None,
    },
    {
        "id": 1010,
        "tool_name": "payment_execute",
        "tool_type": "finance",
        "description": "付款动作，永久禁止自动执行。",
        "provider": "internal",
        "version": "v1",
        "enabled": False,
        "risk_level": "critical",
        "created_at": None,
    },
    {
        "id": 1011,
        "tool_name": "database_read",
        "tool_type": "database",
        "description": "内部数据库只读查询能力登记。",
        "provider": "internal",
        "version": "v1",
        "enabled": True,
        "risk_level": "low",
        "created_at": None,
    },
    {
        "id": 1012,
        "tool_name": "api_read",
        "tool_type": "api",
        "description": "API 只读调用能力登记，第一阶段不真实调用。",
        "provider": "internal",
        "version": "v1",
        "enabled": True,
        "risk_level": "medium",
        "created_at": None,
    },
]


DEFAULT_BINDINGS = [
    {"employee_code": "tiancai", "tool_id": 1001, "permission_level": "web_read", "allowed": True, "require_approval": True},
    {"employee_code": "tiancai", "tool_id": 1004, "permission_level": "file_read", "allowed": True, "require_approval": False},
    {"employee_code": "tiancai", "tool_id": 1011, "permission_level": "read_only", "allowed": True, "require_approval": False},
    {"employee_code": "tiancai", "tool_id": 1012, "permission_level": "read_only", "allowed": True, "require_approval": True},
    {"employee_code": "tiancai", "tool_id": 1009, "permission_level": "forbidden", "allowed": False, "require_approval": True},
    {"employee_code": "tiancai_data", "tool_id": 1001, "permission_level": "web_read", "allowed": True, "require_approval": True},
    {"employee_code": "tiancai_data", "tool_id": 1004, "permission_level": "file_read", "allowed": True, "require_approval": False},
    {"employee_code": "tiancai_data", "tool_id": 1011, "permission_level": "read_only", "allowed": True, "require_approval": False},
    {"employee_code": "tiancai_data", "tool_id": 1012, "permission_level": "read_only", "allowed": True, "require_approval": True},
    {"employee_code": "tiancai_data", "tool_id": 1009, "permission_level": "forbidden", "allowed": False, "require_approval": True},
    {"employee_code": "tianchuang", "tool_id": 1005, "permission_level": "vision_read", "allowed": True, "require_approval": False},
    {"employee_code": "tianyu", "tool_id": 1007, "permission_level": "analysis", "allowed": True, "require_approval": False},
    {"employee_code": "tiancai_finance", "tool_id": 1008, "permission_level": "finance_read", "allowed": True, "require_approval": True},
    {"employee_code": "tiancai_finance", "tool_id": 1010, "permission_level": "forbidden", "allowed": False, "require_approval": True},
]

