from __future__ import annotations

SKILL_TYPES = [
    "数据采集",
    "数据分析",
    "内容生成",
    "浏览器只读",
    "浏览器操作",
    "电脑操作",
    "手机操作",
    "文件处理",
    "数据库操作",
    "Git 操作",
    "Docker 操作",
    "搜索研究",
    "知识检索",
    "视频处理",
    "图片处理",
    "客服",
    "商品运营",
    "广告运营",
    "财务",
    "法务",
    "安全",
    "其他",
]

SKILL_STATUSES = [
    "草稿",
    "待审核",
    "已批准",
    "已发布",
    "已安装",
    "已启用",
    "已停用",
    "已废弃",
    "已撤销",
]

SKILL_RISK_LEVELS = ["低风险", "中风险", "高风险", "极高风险"]
INSTALLATION_STATUSES = [
    "待校验",
    "等待审批",
    "已批准",
    "安装中",
    "已安装",
    "已启用",
    "已停用",
    "安装失败",
    "已卸载",
    "已撤销",
]
INVOCATION_STATUSES = [
    "待校验",
    "等待审批",
    "等待执行",
    "执行中",
    "执行成功",
    "执行失败",
    "已取消",
    "已超时",
]

DEFAULT_SKILL_ENGINE_FEATURES = {
    "SKILLS_ENGINE_ENABLED": False,
    "SKILL_INSTALLATION_ENABLED": False,
    "SKILL_INVOCATION_ENABLED": False,
    "THIRD_PARTY_SKILLS_ENABLED": False,
    "UNSIGNED_SKILLS_ENABLED": False,
    "AUTO_SKILL_UPDATE_ENABLED": False,
    "SKILL_MARKETPLACE_ENABLED": False,
}

DEFAULT_AGENT_FEATURES = {
    "AGENT_RUNTIME_ENABLED": True,
    "REAL_EXECUTOR_ENABLED": False,
    "COMPUTER_CONTROL_ENABLED": False,
    "MOBILE_CONTROL_ENABLED": False,
    "BROWSER_CONTROL_ENABLED": False,
    "BROWSER_READONLY_ENABLED": False,
    "SHELL_EXECUTION_ENABLED": False,
    "PUBLIC_RESEARCH_ENABLED": False,
    "PUBLIC_SEARCH_ENABLED": False,
    "KNOWLEDGE_CENTER_ENABLED": False,
    "KNOWLEDGE_SUBMISSION_ENABLED": False,
    "KNOWLEDGE_PUBLISH_ENABLED": False,
    "KNOWLEDGE_LOCAL_SEARCH_ENABLED": False,
    "KNOWLEDGE_VECTOR_SEARCH_ENABLED": False,
}

MOCK_SKILL_DEFINITIONS = [
    {
        "skill_code": "research.public.report_organize",
        "skill_name": "公开研究报告整理",
        "skill_description": "将公开研究结果整理为结构化中文报告，只做只读整理，不访问真实外部系统。",
        "skill_type": "搜索研究",
        "category": "研究分析",
        "risk_level": "低风险",
        "publisher_type": "内部",
        "publisher_name": "天统AI云中台",
        "source_type": "系统内置",
        "source_url": "about:blank",
        "license": "Tiantong Internal",
        "checksum": "builtin-research-report-organize",
        "signature_status": "已验证",
        "required_capabilities": ["research.public.multi_source", "browser.public.read"],
        "required_permissions": ["skills.read"],
        "required_feature_flags": ["PUBLIC_RESEARCH_ENABLED", "BROWSER_READONLY_ENABLED"],
        "allowed_employee_codes": ["tiancai_data", "tiancai", "tianshu", "tiance_strategy"],
        "timeout_seconds": 20,
        "max_retries": 1,
    },
    {
        "skill_code": "knowledge.local.search",
        "skill_name": "已发布知识检索",
        "skill_description": "检索已发布知识资产，只读返回匹配结果和引用摘要，不修改知识库。",
        "skill_type": "知识检索",
        "category": "知识中心",
        "risk_level": "低风险",
        "publisher_type": "内部",
        "publisher_name": "天统AI云中台",
        "source_type": "系统内置",
        "source_url": "about:blank",
        "license": "Tiantong Internal",
        "checksum": "builtin-knowledge-search",
        "signature_status": "已验证",
        "required_capabilities": ["knowledge.local.search"],
        "required_permissions": ["skills.read"],
        "required_feature_flags": ["KNOWLEDGE_LOCAL_SEARCH_ENABLED"],
        "allowed_employee_codes": ["tiancang", "tiancai_data", "tianshu", "tiance_strategy"],
        "timeout_seconds": 20,
        "max_retries": 1,
    },
    {
        "skill_code": "computer.sandbox.status_check",
        "skill_name": "隔离桌面状态检查",
        "skill_description": "仅检查隔离测试桌面的窗口、屏幕和状态，不控制真实电脑。",
        "skill_type": "电脑操作",
        "category": "电脑执行器",
        "risk_level": "低风险",
        "publisher_type": "内部",
        "publisher_name": "天统AI云中台",
        "source_type": "系统内置",
        "source_url": "about:blank",
        "license": "Tiantong Internal",
        "checksum": "builtin-computer-sandbox-observe",
        "signature_status": "已验证",
        "required_capabilities": ["computer.sandbox.observe"],
        "required_permissions": ["skills.read"],
        "required_feature_flags": ["COMPUTER_EXECUTOR_ENABLED", "ISOLATED_DESKTOP_ENABLED"],
        "allowed_employee_codes": ["tiancai_data", "tianshu", "tiance_strategy"],
        "timeout_seconds": 30,
        "max_retries": 0,
    },
]
